name: GEOSP_2021
channels:
  - r
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - affine=2.3.0
  - anyio=3.4.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - bokeh=2.4.1
  - boost-cpp=1.74.0
  - bqplot=0.12.31
  - branca=0.4.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - cairo=1.16.0
  - cartopy=0.20.1
  - cffi=1.14.6
  - cfitsio=3.470
  - cftime=1.5.1.1
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - colorcet=2.0.6
  - cryptography=35.0.0
  - curl=7.79.1
  - cycler=0.10.0
  - cytoolz=0.11.2
  - dask=2021.11.1
  - dask-core=2021.11.1
  - datashader=0.13.0
  - datashape=0.5.4
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - distributed=2021.11.1
  - entrypoints=0.3
  - expat=2.4.1
  - fiona=1.8.20
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2021.11.0
  - gdal=3.3.2
  - geographiclib=1.52
  - geojson=2.5.0
  - geopy=2.2.0
  - geos=3.9.1
  - geotiff=1.7.0
  - geoviews=1.9.2
  - geoviews-core=1.9.2
  - gettext=0.19.8.1
  - googledrivedownloader=0.4
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - here-map-widget-for-jupyter=1.1.3
  - holoviews=1.14.6
  - htmlmin=0.1.12
  - hvplot=0.7.3
  - icc_rt=2019.0.0
  - icu=68.1
  - imagehash=4.2.1
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.3.0
  - ipyfilechooser=0.6.0
  - ipyleaflet=0.15.0
  - ipython_genutils=0.2.0
  - ipytree=0.2.1
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9d
  - jupyter_client=7.0.1
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.7.1
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyter_server=1.13.1
  - jupyterlab=3.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.9.0
  - jupyterlab_widgets=1.0.2
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - leafmap=0.6.0
  - lerc=2.2.1
  - libcurl=7.79.1
  - libdeflate=1.7
  - libffi=3.4.2
  - libgdal=3.3.2
  - libglib=2.68.4
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzip=1.8.0
  - llvmlite=0.37.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - m2w64-bwidget=1.9.10
  - m2w64-bzip2=1.0.6
  - m2w64-expat=2.1.1
  - m2w64-fftw=3.3.4
  - m2w64-flac=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-gsl=2.1
  - m2w64-libiconv=1.14
  - m2w64-libjpeg-turbo=1.4.2
  - m2w64-libogg=1.3.2
  - m2w64-libpng=1.6.21
  - m2w64-libsndfile=1.0.26
  - m2w64-libtiff=4.0.6
  - m2w64-libvorbis=1.3.5
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-libxml2=2.9.3
  - m2w64-mpfr=3.1.4
  - m2w64-openblas=0.2.19
  - m2w64-pcre=8.38
  - m2w64-speex=1.2rc2
  - m2w64-speexdsp=1.2rc3
  - m2w64-tcl=8.6.5
  - m2w64-tk=8.6.5
  - m2w64-tktable=2.10
  - m2w64-wineditline=2.101
  - m2w64-xz=5.2.2
  - m2w64-zlib=1.2.8
  - mapclassify=2.4.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mercantile=1.2.1
  - missingno=0.4.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - msgpack-python=1.0.2
  - msys2-conda-epoch=20160418
  - multimethod=1.4
  - multipledispatch=0.6.0
  - munch=2.5.0
  - nbclassic=0.3.4
  - nbclient=0.5.9
  - nbconvert=5.6.1
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - netcdf4=1.5.8
  - networkx=2.6.3
  - notebook=6.4.6
  - numba=0.54.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - osmapi=1.3.0
  - owslib=0.25.0
  - packaging=21.2
  - palettable=3.3.0
  - pandas-profiling=3.1.0
  - pandoc=2.16.2
  - pandocfilters=1.5.0
  - panel=0.12.4
  - param=1.12.0
  - parso=0.8.2
  - partd=1.2.0
  - patsy=0.5.2
  - pcre=8.45
  - phik=0.11.2
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pixman=0.40.0
  - plotly=5.4.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.1.1
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - pthread-stubs=0.4
  - pycparser=2.20
  - pycrs=1.0.2
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pydantic=1.8.2
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.18.0
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.8.11
  - python-box=5.4.1
  - python-dateutil=2.8.2
  - python-mss=6.1.0
  - python_abi=3.8
  - pytz=2021.3
  - pyviz_comms=2.1.0
  - pywavelets=1.1.1
  - pywin32=228
  - pywinpty=1.1.6
  - pyzmq=22.2.1
  - r-base=3.6.1
  - r-spatial=7.3_11
  - rasterio=1.2.10
  - requests=2.26.0
  - rtree=0.9.7
  - ruamel.yaml=0.17.17
  - ruamel.yaml.clib=0.2.6
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sniffio=1.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlite=3.36.0
  - statsmodels=0.13.0
  - tangled-up-in-unicode=0.1.0
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.12.1
  - testpath=0.5.0
  - tiledb=2.3.4
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.0
  - traittypes=0.2.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - ucrt=10.0.20348.0
  - urllib3=1.26.7
  - vc=14.2
  - visions=0.7.4
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.0
  - whitebox=2.0.3
  - whiteboxgui=0.6.0
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xarray=0.20.1
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-xproto=7.0.31
  - xyzservices=2021.11.0
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - alphashape==1.3.1
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - atomicwrites==1.4.0
    - beautifulsoup4==4.10.0
    - bmi-arcgis-restapi==2.1.2
    - certifi==2021.10.8
    - charset-normalizer==2.0.6
    - click-log==0.3.2
    - colour==0.1.5
    - contextily==1.1.0
    - cykhash==1.0.2
    - cython==0.29.24
    - dms2dec==0.1
    - folium==0.12.1
    - geopandas==0.10.1
    - gpxpy==1.5.0
    - idna==3.2
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - ipyevents==0.9.0
    - ipykernel==6.4.1
    - ipython==7.28.0
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.2.1
    - lxml==4.6.4
    - movingpandas==0.7rc1
    - nodejs==0.1.1
    - notebook-as-pdf==0.5.0
    - numexpr==2.7.3
    - numpy==1.20.0
    - optional-django==0.1.0
    - osmium==3.2.0
    - osmnx==1.1.1
    - pandana==0.6.1
    - pandas==1.3.3
    - pip==21.3.1
    - pluggy==1.0.0
    - py==1.11.0
    - pyarrow==6.0.1
    - pyee==8.2.2
    - pygeos==0.10.2
    - pypdf2==1.26.0
    - pyppeteer==1.0.1
    - pyproj==3.3.0
    - pyrobuf==0.9.3
    - pyrosm==0.6.1
    - pytest==6.2.5
    - pytest-sugar==0.9.4
    - python-rapidjson==1.5
    - python-snappy==0.6.0
    - pyyaml==6.0
    - retrying==1.3.3
    - rioxarray==0.5.0
    - seaborn==0.11.1
    - shapely==1.7.1
    - soupsieve==2.3.1
    - spatialpandas==0.4.3
    - tables==3.6.1
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - trimesh==3.9.32
    - ujson==4.2.0
    - websockets==10.1
    - xarray-spatial==0.2.9
    - xlrd==2.0.1
